"use client";
import Link from "next/link";
import {AppShell} from "@/components/AppShell";
import {usePlatformStore} from "@/lib/store/platformStore";
import {overview,repPerformance,territoryPerformance,lifecycleFunnel,financeSummary,money} from "@/lib/reporting/metrics";
const pct=(v:number)=>`${(v*100).toFixed(1)}%`;
export default function ReportsPage(){const {data}=usePlatformStore();const o=overview(data),reps=repPerformance(data).slice(0,5),terr=territoryPerformance(data).slice(0,5),life=lifecycleFunnel(data),fin=financeSummary(data);return <AppShell>
<div className="page-header"><div><div className="eyebrow">Reporting & Analytics</div><h1>Operations Dashboard</h1><p className="muted">Management visibility across sales, scheduling, lifecycle, and finance.</p></div><Link className="button secondary" href="/admin/reporting">Reporting settings</Link></div>
<div className="grid metric-grid"><div className="card"><div className="eyebrow">Sales attempts</div><div className="metric">{o.attempts}</div></div><div className="card"><div className="eyebrow">Orders</div><div className="metric">{o.orders}</div></div><div className="card"><div className="eyebrow">Conversion</div><div className="metric">{pct(o.conversion)}</div></div><div className="card"><div className="eyebrow">Invoice value</div><div className="metric">{money(o.invoiceValue)}</div></div><div className="card"><div className="eyebrow">Open exceptions</div><div className="metric">{o.exceptions}</div></div></div>
<div className="grid two-column section-block"><section className="card table-card"><div className="section-heading compact"><div><div className="eyebrow">Sales Performance</div><h2>Representatives</h2></div><Link className="text-link" href="/reports/reps">Full report</Link></div>{reps.length===0?<div className="empty-state">No sales activity yet.</div>:<table><thead><tr><th>Rep</th><th>Team</th><th>Attempts</th><th>Orders</th><th>Conv.</th></tr></thead><tbody>{reps.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.team}</td><td>{r.attempts}</td><td>{r.orders}</td><td>{pct(r.conversion)}</td></tr>)}</tbody></table>}</section>
<section className="card table-card"><div className="section-heading compact"><div><div className="eyebrow">Territory Performance</div><h2>Territories</h2></div><Link className="text-link" href="/reports/territories">Full report</Link></div>{terr.length===0?<div className="empty-state">No territory activity yet.</div>:<table><thead><tr><th>Territory</th><th>Market</th><th>Attempts</th><th>Orders</th><th>Conv.</th></tr></thead><tbody>{terr.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.market}</td><td>{r.attempts}</td><td>{r.orders}</td><td>{pct(r.conversion)}</td></tr>)}</tbody></table>}</section></div>
<div className="grid two-column section-block"><section className="card"><div className="section-heading compact"><div><div className="eyebrow">Lifecycle Funnel</div><h2>Current stages</h2></div><Link className="text-link" href="/reports/lifecycle">Lifecycle report</Link></div><div className="report-bars">{life.map(r=>{const max=Math.max(1,...life.map(x=>x.count));return <div className="report-bar-row" key={r.id}><div className="report-bar-label"><span>{r.name}</span><strong>{r.count}</strong></div><div className="report-bar-track"><div className="report-bar-fill" style={{width:`${Math.max(4,r.count/max*100)}%`}} /></div></div>})}</div></section>
<section className="card"><div className="section-heading compact"><div><div className="eyebrow">Scheduling</div><h2>Appointment outcomes</h2></div><Link className="text-link" href="/reports/scheduling">Scheduling report</Link></div><div className="summary-list"><div><span>Booked / active</span><strong>{o.booked}</strong></div><div><span>Completed</span><strong>{o.completed}</strong></div><div><span>Cancelled</span><strong>{o.cancelled}</strong></div><div><span>No show</span><strong>{o.noShow}</strong></div></div></section></div>
<section className="card section-block"><div className="section-heading compact"><div><div className="eyebrow">Finance</div><h2>Invoice performance</h2></div><Link className="text-link" href="/reports/finance">Finance report</Link></div><div className="grid compact-metrics"><div><span>Batches</span><strong>{fin.batches}</strong></div><div><span>Subtotal</span><strong>{money(fin.subtotal)}</strong></div><div><span>Adjustments</span><strong>{money(fin.adjustments)}</strong></div><div><span>Total</span><strong>{money(fin.total)}</strong></div></div></section>
</AppShell>}
