export type InvoiceExportLine = {
  customer: string;
  location: string;
  description: string;
  amount: number;
  orderId: string;
};

export type InvoiceExportAdjustment = {
  description: string;
  amount: number;
};

export type InvoiceExportInput = {
  organizationName: string;
  invoiceNumber: string;
  status: string;
  createdAt: string;
  currency: string;
  subtotal: number;
  adjustmentsTotal: number;
  total: number;
  lines: InvoiceExportLine[];
  adjustments: InvoiceExportAdjustment[];
};

function csvCell(value: string | number) {
  const s = String(value ?? "");
  return `"${s.replaceAll('"', '""')}"`;
}

export function buildInvoiceCsv(
  input: InvoiceExportInput
) {
  const rows = [
    ["Invoice Number", input.invoiceNumber],
    ["Organization", input.organizationName],
    ["Status", input.status],
    ["Created", input.createdAt],
    [],
    [
      "Order ID",
      "Customer",
      "Location",
      "Description",
      "Amount",
    ],
    ...input.lines.map((line) => [
      line.orderId,
      line.customer,
      line.location,
      line.description,
      line.amount.toFixed(2),
    ]),
    [],
    ["Subtotal", input.subtotal.toFixed(2)],
    [
      "Adjustments",
      input.adjustmentsTotal.toFixed(2),
    ],
    ["Total", input.total.toFixed(2)],
  ];

  return rows
    .map((row) =>
      row.map(csvCell).join(",")
    )
    .join("\r\n");
}

function ascii(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, " ")
    .replaceAll("\\", "\\\\")
    .replaceAll("(", "\\(")
    .replaceAll(")", "\\)");
}

function money(
  value: number,
  currency: string
) {
  return `${currency} ${value.toFixed(2)}`;
}

type PdfLine = {
  text: string;
  size?: number;
  gap?: number;
};

export function buildInvoicePdf(
  input: InvoiceExportInput
): Uint8Array {
  const lines: PdfLine[] = [
    {
      text: input.organizationName,
      size: 16,
      gap: 22,
    },
    {
      text: `Invoice ${input.invoiceNumber}`,
      size: 14,
      gap: 20,
    },
    {
      text: `Status: ${input.status}`,
      gap: 14,
    },
    {
      text: `Created: ${new Date(
        input.createdAt
      ).toLocaleString()}`,
      gap: 14,
    },
    {
      text: "",
      gap: 12,
    },
    {
      text: "Line Items",
      size: 12,
      gap: 18,
    },

    ...input.lines.flatMap(
      (line, index) => [
        {
          text: `${index + 1}. ${
            line.customer
          } - ${line.description}`,
          gap: 14,
        },
        {
          text: `   ${line.location}`,
          gap: 13,
        },
        {
          text: `   ${
            line.orderId
          }   ${money(
            line.amount,
            input.currency
          )}`,
          gap: 15,
        },
      ]
    ),

    {
      text: "",
      gap: 10,
    },

    {
      text: `Subtotal: ${money(
        input.subtotal,
        input.currency
      )}`,
      size: 11,
      gap: 16,
    },

    ...input.adjustments.map(
      (adjustment) => ({
        text: `Adjustment: ${
          adjustment.description
        }  ${money(
          adjustment.amount,
          input.currency
        )}`,
        gap: 14,
      })
    ),

    {
      text: `Adjustments total: ${money(
        input.adjustmentsTotal,
        input.currency
      )}`,
      gap: 16,
    },

    {
      text: `TOTAL: ${money(
        input.total,
        input.currency
      )}`,
      size: 14,
      gap: 20,
    },

    {
      text: "",
      gap: 12,
    },

    {
      text: "Generated by Cwlwm Field Operations",
      size: 9,
      gap: 12,
    },
  ];

  const pages: PdfLine[][] = [];

  let current: PdfLine[] = [];
  let used = 0;

  for (const line of lines) {
    const gap = line.gap ?? 14;

    if (
      used + gap > 680 &&
      current.length
    ) {
      pages.push(current);
      current = [];
      used = 0;
    }

    current.push(line);
    used += gap;
  }

  if (current.length) {
    pages.push(current);
  }

  const objects: string[] = [];

  const pageRefs = pages
    .map(
      (_, index) =>
        `${4 + index * 2} 0 R`
    )
    .join(" ");

  objects[0] =
    "<< /Type /Catalog /Pages 2 0 R >>";

  objects[1] =
    `<< /Type /Pages /Kids [${pageRefs}] /Count ${pages.length} >>`;

  objects[2] =
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

  pages.forEach(
    (pageLines, index) => {
      let y = 742;

      const commands: string[] = [
        "BT",
      ];

      for (const line of pageLines) {
        const size = line.size ?? 10;

        commands.push(
          `/F1 ${size} Tf`
        );

        commands.push(
          `1 0 0 1 50 ${y} Tm`
        );

        commands.push(
          `(${ascii(line.text)}) Tj`
        );

        y -= line.gap ?? 14;
      }

      commands.push("ET");

      const stream =
        commands.join("\n");

      const pageObj =
        4 + index * 2;

      const contentObj =
        pageObj + 1;

      objects[pageObj - 1] =
        `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentObj} 0 R >>`;

      objects[contentObj - 1] =
        `<< /Length ${
          new TextEncoder().encode(
            stream
          ).length
        } >>\nstream\n${stream}\nendstream`;
    }
  );

  let pdf = "%PDF-1.4\n";

  const offsets = [0];

  for (
    let i = 0;
    i < objects.length;
    i++
  ) {
    offsets[i + 1] =
      new TextEncoder().encode(
        pdf
      ).length;

    pdf += `${i + 1} 0 obj\n${
      objects[i]
    }\nendobj\n`;
  }

  const xrefOffset =
    new TextEncoder().encode(
      pdf
    ).length;

  pdf +=
    `xref\n0 ${
      objects.length + 1
    }\n`;

  pdf +=
    "0000000000 65535 f \n";

  for (
    let i = 1;
    i <= objects.length;
    i++
  ) {
    pdf += `${String(
      offsets[i]
    ).padStart(
      10,
      "0"
    )} 00000 n \n`;
  }

  pdf +=
    `trailer\n<< /Size ${
      objects.length + 1
    } /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new TextEncoder().encode(
    pdf
  );
}

export function downloadBytes(
  bytes: Uint8Array,
  filename: string,
  mime: string
) {
  const buffer =
    bytes.buffer.slice(
      bytes.byteOffset,
      bytes.byteOffset +
        bytes.byteLength
    ) as ArrayBuffer;

  const blob = new Blob(
    [buffer],
    {
      type: mime,
    }
  );

  const url =
    URL.createObjectURL(
      blob
    );

  const anchor =
    document.createElement("a");

  anchor.href = url;
  anchor.download = filename;

  document.body.appendChild(
    anchor
  );

  anchor.click();
  anchor.remove();

  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 1000);
}

export function downloadText(
  text: string,
  filename: string,
  mime: string
) {
  const bytes =
    new TextEncoder().encode(
      text
    );

  downloadBytes(
    bytes,
    filename,
    mime
  );
}